# DEEP LEARNING
# TUẦN 2: NUMPY, PANDAS, MATPLOTLIB

# NUMPY

In [1]:
# NUMPY là thư viện kiểu list
# vì: 
#+ numpy nhanh
#+ có nhiều hàm tích hợp dễ sử dụng cho AI

#đế sử dụng numpy thì : pip install numpy 

import numpy as np

In [2]:
#thử tạo 1 list

python_list = [1, 2, 3]

# chuyển đổi danh sách trên thành numpy list
numpy_list = np. array (python_list)
type (numpy_list) 

numpy.ndarray

In [3]:
# list trong python sau có thể hỗ trơ nhiều loại dữ liệu trong list
my_list = [1, "chào", True,2.0]

In [4]:
my_list = [ 1, 2, 3, 4, 5]
np_list = np.array(my_list)
np_list

array([1, 2, 3, 4, 5])

In [5]:
# Chuyến đói kiếu dữ liệu thì sao?
np_list_int = np_list.astype(int) 
np_list_int

array([1, 2, 3, 4, 5])

In [6]:
# accesscing và indexing

x = np.array ([1, 2, 3, 4, 5, 6, 7, 8]) # x = np.array(range(1, 9))

In [8]:
# lấy số 4
x[3]

5

In [12]:
# lấy nhiều hơn một phần tử
# công thức[start:end:step]
# lấy 1, 2, 3
x[0:3]
# lấy từ 3 đến 8 theo 3 cách?
#C1:
x[2:8]

array([4, 5, 6, 7, 8])

In [13]:
#C2:
x[2:]

array([3, 4, 5, 6, 7, 8])

In [18]:
#C3 - không dúng:
x[2:-1]

array([3, 4, 5, 6, 7])

In [15]:
#C3:
x[2:8:1]

array([3, 4, 5, 6, 7, 8])

In [19]:
# lấy số 3 và số 5
x[2], x[4]

(3, 5)

In [20]:
# đặt danh sách các index muốn truy cập
x[[2,4]]

array([3, 5])

In [22]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
#lấy số 2
np_list[0, 1]

2

In [25]:
#lấy số 6
np_list[2, 1]

6

In [26]:
#lấy số [3, 4], [5, 6]

#C1
np_list[1:,: ]

array([[3, 4],
       [5, 6]])

In [29]:
#C2
np_list[[1, 2],:]

array([[3, 4],
       [5, 6]])

In [32]:
#C3
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [38]:
# lấy 1, 3, 5
np_list[0:3, 0]

array([1, 3, 5])

In [42]:
# lấy 1 và 5
np_list[[0, 2], 0]

array([1, 5])

BTVN

In [65]:
x = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
# lấy 2, 6, 10, 14
np_list[:, 1]

array([ 2,  6, 10, 14])

In [67]:
# lấy 7 và 11
np_list[[1, 2], 2]

array([ 7, 11])

In [75]:
# lấy 16, 15, 14, 13
np_list[[3, 3, 3, 3], [3, 2, 1, 0]]

array([16, 15, 14, 13])

In [79]:
np_list[3,::-1]

array([16, 15, 14, 13])

In [82]:
np_list[-1, ::-1]

array([16, 15, 14, 13])

In [1]:
# BTVN thú vị

# Cho ma trận = [[99, 99, 99],
#            [99, 99, 99],
#            [99, 99, 99]]

# Hãy tưởng tượng ô 99 trống
# Giả sử: 1 là x
# Giả sử: 0 là o

# Lấy đầu vào từ phía x và phía o luân phiên
# Nếu đầu vào từ phía x alf o,o

# Thì ma trận sẽ trở thành 
# [[x, 99, 99],
# [99, 99, 99],
# [99, 99, 99]]

# Nếu đầu vào từ phía o cũng là (o, o)
# Thông báo họ nhập lại
# Nếu không thì điền vào ma trận

# Thử thách: Nếu người đầu tiên có 3 phần tử liên tiếp hãy dừng trò chơi

# BTVN thú vị: X/O trên ma trận 3x3
# 99 là ô trống
# x = 1
# o = 0
# nhập (row,col) luân phiên
# nếu ô đã có người đánh => nhập lại
# nếu ai có 3 phần tử liên tiếp => dừng game

import numpy as np

board = np.array([
    [99, 99, 99],
    [99, 99, 99],
    [99, 99, 99]
])

current = 1   # x đi trước (1), o là 0

print("Game bắt đầu! Nhập dạng row,col (0..2). Ví dụ: 0,0")

while True:
    # in board: 99 -> .
    show = board.copy().astype(object)
    show[show == 99] = "."
    show[show == 1] = "x"
    show[show == 0] = "o"
    print(show)

    player_char = "x" if current == 1 else "o"
    s = input(f"Lượt {player_char}, nhập (row,col): ").strip()

    # tách row,col
    try:
        r, c = s.split(",")
        r = int(r.strip())
        c = int(c.strip())
    except:
        print("Sai định dạng! Nhập lại kiểu row,col (ví dụ 1,2)")
        continue

    # kiểm tra biên
    if r < 0 or r > 2 or c < 0 or c > 2:
        print("Tọa độ không hợp lệ! Chỉ 0..2. Nhập lại!")
        continue

    # kiểm tra ô trống
    if board[r, c] != 99:
        print("Ô này đã có người đánh rồi. Nhập lại!")
        continue

    # điền vào ma trận
    board[r, c] = current

    # kiểm tra thắng (3 liên tiếp)
    win = False

    # hàng / cột
    for i in range(3):
        if np.all(board[i, :] == current):
            win = True
        if np.all(board[:, i] == current):
            win = True

    # chéo chính / chéo phụ
    if np.all(np.diag(board) == current):
        win = True
    if np.all(np.diag(np.fliplr(board)) == current):
        win = True

    if win:
        show = board.copy().astype(object)
        show[show == 99] = "."
        show[show == 1] = "x"
        show[show == 0] = "o"
        print(show)
        print(f"🎉 {player_char.upper()} thắng! Dừng trò chơi.")
        break

    # kiểm tra hòa (hết ô trống)
    if not np.any(board == 99):
        show = board.copy().astype(object)
        show[show == 99] = "."
        show[show == 1] = "x"
        show[show == 0] = "o"
        print(show)
        print("🤝 Hòa! Bảng đã đầy.")
        break

    # đổi lượt
    current = 0 if current == 1 else 1



Game bắt đầu! Nhập dạng row,col (0..2). Ví dụ: 0,0
[['.' '.' '.']
 ['.' '.' '.']
 ['.' '.' '.']]
[['x' '.' '.']
 ['.' '.' '.']
 ['.' '.' '.']]
[['x' 'o' '.']
 ['.' '.' '.']
 ['.' '.' '.']]
[['x' 'o' 'x']
 ['.' '.' '.']
 ['.' '.' '.']]
Sai định dạng! Nhập lại kiểu row,col (ví dụ 1,2)
[['x' 'o' 'x']
 ['.' '.' '.']
 ['.' '.' '.']]


In [6]:
# BTVN 2
# Cho y = [
        # [1, 2, 3], 
        # [4, 5, 6], 
        # [7, 8, 9]
        # ]

#Lấy 4, 5, 6
#Lấy 2, 5
#Lấy 3, 4
#Lấy 9, 6, 3

import numpy as np

y = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

#Lấy 4, 5, 6
y[1, :]


array([4, 5, 6])

In [3]:
#Lấy 2, 5
#C1
y[0:2, 1]

array([2, 5])

In [4]:
#C2
y[[0, 1], 1]

array([2, 5])

In [5]:
#Lấy 3, 4
[y[0, 2], y[1, 0]]

[3, 4]

In [7]:
#Lấy 9, 6, 3
#C1
y[::-1, 2]

array([9, 6, 3])

In [8]:
#C2
y[[2, 1, 0], 2]

array([9, 6, 3])

In [11]:
#BTVN 3
#Cho x = [1,2,3,4,5,6,7,8,9,10]

#1. Xuất ra các giá trị chẵn sử dụng if
#2. Xuất ra các giá trị chẵn sử dụng list comprehension

import numpy as np

np_x = np.arange(1, 11)
np_x

for i in np_x:
    if i % 2 == 0:
        print(i)

[i for i in np_x if i % 2 == 0]

np_x[np_x % 2 == 0]


2
4
6
8
10


array([ 2,  4,  6,  8, 10])

In [83]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [85]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
idx = [True, True, True, False, True, True, True, False, True, False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [87]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 % cond2 | cond3]

C:\Users\ACER\AppData\Local\Temp\ipykernel_12520\1188049316.py:5: RuntimeWarning: divide by zero encountered in remainder
  np_x[cond1 % cond2 | cond3]


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
# BTVN 4
# Tạo một mảng numpy với kích thước 150 x 5. Giả sử mã này chứa 150 mẫu dữ liệu của sinh viên bao gồm:
# Chiều cao, cân nặng, tuổi, lương và điểm trung bình
# Tách mãng dựa trên 4 cột đầu tiên thành một biến có tên là X và cột cuối cùng thành y
# Tách mã x thành X_train và X_test. Trong đó X_train chứa 70% dữ liệu và tách y thành Y_train và Y_test, trong đó Y_train chứa 70% dữ liệu

#Tạo 10 tập dữ liệu X_train không chéo nhau

import numpy as np

np.random.seed(42)

data = np.random.rand(150, 5)
data

X = data[:, :4]
y = data[:, 4]

X
y

n_train = int(0.7 * len(X))
n_train

X_train = X[:n_train]
X_test  = X[n_train:]

y_train = y[:n_train]
y_test  = y[n_train:]

X_train.shape
X_test.shape
y_train.shape
y_test.shape

X_train_sets = np.array_split(X_train, 10)

for i, subset in enumerate(X_train_sets):
    print(f"Tap {i+1}: shape =", subset.shape)

data = np.random.rand(150, 5)

X = data[:, :4]
y = data[:, 4]

X_train = X[:105]
X_test  = X[105:]

X_train_sets = np.array_split(X_train, 10)


Tap 1: shape = (11, 4)
Tap 2: shape = (11, 4)
Tap 3: shape = (11, 4)
Tap 4: shape = (11, 4)
Tap 5: shape = (11, 4)
Tap 6: shape = (10, 4)
Tap 7: shape = (10, 4)
Tap 8: shape = (10, 4)
Tap 9: shape = (10, 4)
Tap 10: shape = (10, 4)
