# DEEP LEARNING

## Pytorch Basic

In [6]:
import torch

In [7]:
torch.cuda.is_available()

False

## Dataset with pytorch

In [8]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
df = pd.read_csv("Iris.csv")


In [14]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
x = df.drop(['Species'], axis=1).values
y = le.fit_transform(df["Species"].values)
                     
#chia du lieu voi test size = 20%

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
x_train = torch.FloatTensor (x_train)
x_test = torch.FloatTensor (x_test)
y_train = torch.LongTensor (y_train).reshape(-1,1)
y_test = torch.LongTensor (y_test).reshape(-1,1)


In [15]:
len(y_train)

30

In [16]:
labels, counts = y_train. unique (return_counts=True) 
print(labels, counts)

tensor([0, 1, 2]) tensor([10, 11,  9])


In [17]:
# Tính đạo hàm bàng pytorch
# cho y 2x^4 + x^3 + 3x^2+ 1
# Tính y

In [18]:
import torch

In [19]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [20]:
#Dinh nghia ham
y = 2*x**4 + x**3 + 3*x**2 +5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [21]:
#thuc hien ham truyen nguoc va tinh toan cac gradient

y.backward()

In [22]:
#8x^3 + 3x^2 +7x + 5

x.grad

tensor(93.)

### BTVN
</br> Cho y = 5x^5 + 6x^3 - 3x+1
</br> Cho biet do doc cua da thuc tren o diem nao

In [33]:
import torch
#khai báo biến x tại điểm cần tính đạo hàm
x = torch.tensor(2.0, requires_grad=True)

#Định nghĩa hàm y
y = 5*x**5 + 6*x**3 - 3*x + 1

#Tính đạo hàm
y.backward()

#In kết quả
print("Giá trị y tại x =", x.item(), ":", y.item())
print("Độ dốc của đa thức tại x =", x.item(), ":", x.grad.item())


Giá trị y tại x = 2.0 : 203.0
Độ dốc của đa thức tại x = 2.0 : 469.0


# BTVN 02:
</br> Tạo một tensor ban đầu có giá tri la 2
</br> Định nghĩa hàm số và tính gradient
</br> y -x^3+2x ^ 2 + 5x +1
</br> hãy tính dy/dx tại giá trị cúa x
</br> Dùng_phương pháp Gradient Descent với Learning rate alpha - 0.1 dể cập nhật giá trí x trong 10 vòng lặp 

# BTVN 03;
</br> Tạo một tập dữ liệu gia lập vói x la số giờ học(ngẫu nhiên từ 1 - 10 ) va y la số điểm dược tính thep. Voi noise la mot gia tri nga nhien nho
</br> 1 Khoi tao tham so x va b ngau nhien voi requires=true 2 
</br> 2 Tinh MSE
</br> 3 Tinh Gradient 
</br> 4 Tinh cap nhat tham so w va b = gradient
</br> 5 Lap lai qua trinh tren trong 101 lan de xem su hoi tu cua mo hinh

In [34]:
#BTVN 2

import torch
#Khởi tạo x 
x = torch.tensor(2.0, requires_grad=True)
#Learning rate
alpha = 0.1
print("Giá trị x ban đầu:", x.item())
print("-" * 40)
#Gradient Descent trong 10 vòng lặp
for i in range(10):
    #Định nghĩa hàm y
    y = x**3 + 2*x**2 + 5*x + 1
    #Tính gradient
    y.backward()
    with torch.no_grad():
        x -= alpha * x.grad
    x.grad.zero_()
    #In kết quả mỗi vòng
    print(f"Vòng {i+1}: x = {x.item():.6f}, y = {y.item():.6f}")

Giá trị x ban đầu: 2.0
----------------------------------------
Vòng 1: x = -0.500000, y = 27.000000
Vòng 2: x = -0.875000, y = -1.125000
Vòng 3: x = -1.254688, y = -2.513672
Vòng 4: x = -1.725085, y = -4.100136
Vòng 5: x = -2.427826, y = -6.807298
Vòng 6: x = -3.724998, y = -13.660884
Vòng 7: x = -6.897680, y = -41.560375
Vòng 8: x = -18.912006, y = -266.510193
Vòng 9: x = -119.146408, y = -6142.375000
Vòng 10: x = -4330.747559, y = -1663589.500000


In [35]:
#BTVN 3
import torch
import random

torch.manual_seed(42)

x = torch.rand(50, 1) * 9 + 1       
noise = torch.randn(50, 1) * 0.5 
y = 2 * x + 3 + noise             

w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

#Learning rate
alpha = 0.01

for epoch in range(101):
    #Dự đoán
    y_pred = w * x + b
    
    #Tính MSE
    loss = torch.mean((y_pred - y) ** 2)
    
    #Tính gradient
    loss.backward()
    
    #Cập nhật tham số
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    
    #Reset gradient
    w.grad.zero_()
    b.grad.zero_()
    
    #In kết quả mỗi 10 vòng
    if epoch % 10 == 0:
        print(f"Epoch {epoch:3d}: Loss = {loss.item():.4f}, w = {w.item():.4f}, b = {b.item():.4f}")


Epoch   0: Loss = 409.6038, w = 2.0774, b = -0.1867
Epoch  10: Loss = 1.4602, w = 2.4436, b = -0.0497
Epoch  20: Loss = 1.3928, w = 2.4321, b = 0.0314
Epoch  30: Loss = 1.3291, w = 2.4209, b = 0.1103
Epoch  40: Loss = 1.2688, w = 2.4100, b = 0.1870
Epoch  50: Loss = 1.2118, w = 2.3994, b = 0.2616
Epoch  60: Loss = 1.1578, w = 2.3891, b = 0.3341
Epoch  70: Loss = 1.1069, w = 2.3791, b = 0.4047
Epoch  80: Loss = 1.0586, w = 2.3693, b = 0.4733
Epoch  90: Loss = 1.0130, w = 2.3599, b = 0.5400
Epoch 100: Loss = 0.9699, w = 2.3507, b = 0.6049


### BTVN 4:

In [24]:
# chuyến đổi màng numpy sang tensor pytorch
arr = np.array([1,2,3,4,5])
print(arr) 
print(arr.dtype) 
print(type(arr)) 

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [25]:
print(x.dtype)

torch.float32


In [26]:
print(x.type())

torch.FloatTensor


In [27]:
arr2 = np.arange(0.,12.).reshape(4,3) 
arr2  

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [28]:
arr[0] = 99 
print(x)

tensor(2., requires_grad=True)


In [29]:
arr = np.arange(0,5) 
x = torch.tensor(arr) 
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


In [30]:
arr[0]=99
print(x)

tensor([0, 1, 2, 3, 4], dtype=torch.int32)


### BTVN 04: Giải thích 2 trường hợp ở trên

Giải thích:

Trong trường hợp sử dụng torch.from_numpy(), tensor PyTorch và mảng NumPy dùng chung vùng nhớ nên khi mảng NumPy thay đổi, tensor cũng thay đổi theo.

Trong trường hợp sử dụng torch.tensor(), dữ liệu được sao chép sang vùng nhớ mới nên việc thay đổi mảng NumPy không ảnh hưởng đến tensor PyTorch.

### BTVN 05
Bạn giúp thầy tạo tensor với 
</br> empyty
</br> zeros 
</br> ones
</br> random
</br> Reshape với view và view as

In [32]:
import torch

#Tạo tensor với empty
x_empty = torch.empty(3, 4)

print(x_empty)
print(x_empty.shape)

#Tạo tensor với zeros
x_zeros = torch.zeros(3, 4)

print(x_zeros)
print(x_zeros.shape)

#Tạo tensor với ones
x_ones = torch.ones(3, 4)

print(x_ones)
print(x_ones.shape)

#Tạo tensor với random
x_rand = torch.rand(3, 4)

print(x_rand)
print(x_rand.shape)

#Reshape với view
x = torch.arange(0, 12)

print(x)
print(x.shape)

x_view = x.view(3, 4)
print(x_view)
print(x_view.shape)

#Reshape với view_as
y = torch.zeros(3, 4)

x_view_as = x.view_as(y)

print(x_view_as)
print(x_view_as.shape)

tensor([[2.5226e+32, 1.9170e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
torch.Size([3, 4])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 4])
tensor([[0.8406, 0.5650, 0.5467, 0.6170],
        [0.0658, 0.8667, 0.8217, 0.6443],
        [0.0342, 0.8272, 0.1978, 0.8532]])
torch.Size([3, 4])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
